import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'manantiales',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en" data-theme='cupcake'>
			<body className={`${inter.className} min min-h-screen bg-base-100`}>
				<div className="navbar bg-base-300 shadow">
					<div className="navbar-start">
						<div className="dropdown">
							<label tabIndex={0} className="btn btn-ghost btn-circle">
								<svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 12h16M4 18h7" /></svg>
							</label>
							<ul tabIndex={0} className="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52">
								<li><a>Homepage</a></li>
								<li><a>Portfolio</a></li>
								<li><a>About</a></li>
							</ul>
						</div>
					</div>
					<div className="navbar-center">
						<a className="btn btn-ghost text-xl">Manantiales</a>
					</div>
					<div className="navbar-end">
					</div>
				</div>
				{children}
			</body>
		</html>
	)
}
